=== Manuel0119/2122_LMSGI_ManuelMA/ud4/04.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="curriculum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/> 
                <xs:element name="apellido" type="xs:string"/>
                <xs:element name="anyo" type="xs:gYear"/> 
                <xs:element name="residencia"> 
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ciudad" type="xs:string"/> 
                            <xs:element name="pais" type="xs:string"/> 
                        </xs:sequence>
                    </xs:complexType>   
                </xs:element>
                <xs:element name="datos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tel" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="perfil" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/> 
                            <xs:element name="competencias">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="competencia" maxOccurs="unbounded"> 
                                                <xs:complexType>
                                                    <xs:attribute name="nombre" type="xs:string"/>
                                                    <xs:attribute name="nivel" default="medio"> 
                                                        <xs:simpleType>                                                     
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="alto|medio|bajo"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:attribute>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                            </xs:element>  
                             <xs:element name="formaciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="formacion" maxOccurs="unbounded"> 
                                            <xs:complexType> 
                                                <xs:attribute name="titulo" type="xs:string"/>
                                                <xs:attribute name="centro" type="xs:string"/>
                                                <xs:attribute name="anyo" type="xs:gYear" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>  
                            <xs:element name="experiencias">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="experiencia">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="puesto" type="xs:string"/>
                                                    <xs:element name="empresa" type="xs:string"/>
                                                    <xs:element name="anyoini" type="xs:gYear"/>
                                                    <xs:element name="anyofin" type="xs:gYear"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType> 
    </xs:element>
</xs:schema>

=== Manuel0119/2122_LMSGI_ManuelMA/ud4/XML04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE curriculum [
    <!ELEMENT curriculum (nombre,apellido,anyo,residencia,datos)>
    <!ATTLIST curriculum
              xmlns:xsi CDATA #IMPLIED
              xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT residencia (ciudad,pais)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT datos (tel,email,perfil+,descripcion,competencias+,formaciones,experiencias+)>
    <!ELEMENT tel (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT perfil (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT competencias (competencia+)>
    <!ELEMENT competencia EMPTY>
    <!ATTLIST competencia nombre CDATA #REQUIRED
                           nivel (alto|medio|bajo) "medio">
    <!ELEMENT formaciones (formacion+)>
    <!ELEMENT formacion EMPTY>
    <!ATTLIST formacion titulo CDATA #REQUIRED
                        centro CDATA #REQUIRED
                        anyo CDATA #IMPLIED>
    <!ELEMENT experiencias (experiencia+)>
    <!ELEMENT experiencia (puesto,empresa,anyoini,anyofin?)>
    <!ELEMENT puesto (#PCDATA)>
    <!ELEMENT empresa (#PCDATA)>
    <!ELEMENT anyoini (#PCDATA)>
    <!ELEMENT anyofin (#PCDATA)>
    <!ATTLIST puesto especificar CDATA #IMPLIED>
]>  
<curriculum xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='04.xsd'>
    <nombre>Manuel</nombre>
    <apellido>Martin Alonso</apellido>  
    <anyo>2002</anyo>  
    <residencia>
        <ciudad>Benavente</ciudad>
        <pais>Espa√±a</pais>
    </residencia>
    <datos>
        <tel>654213578</tel>
        <email>manuel.maralo.2@educa.jcyl.es</email>
        <perfil>https://es.linkedin.com/ManuelMartin</perfil>
        <descripcion>Buen trabajador</descripcion>
        <competencias>  
            <competencia nombre="Ingles" nivel="medio"></competencia>
        </competencias> 
        <formaciones>
            <formacion titulo="DAW1" centro="IES Los Sauces" anyo="2022"></formacion>
        </formaciones>
        <experiencias>
            <experiencia>
                <puesto>a</puesto>
                <empresa>a</empresa>
                <anyoini>2022</anyoini> 
                <anyofin>2022</anyofin> 
            </experiencia>      
        </experiencias>         
    </datos>
</curriculum>
