<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE receta [
    <!ELEMENT receta (nombre,descripcion?,tiempo,ingredientes,instrucciones)>
    <!ATTLIST receta plato (primero|segundo|postre) #REQUIRED>
    <!ATTLIST receta
            xmlns:xsi CDATA #IMPLIED
            xsi:noNamespaceSchemaLocation CDATA #IMPLIED>      
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT tiempo (#PCDATA)>
    <!ATTLIST tiempo preparacion CDATA #REQUIRED
                     coccion CDATA #IMPLIED>
    <!ELEMENT ingredientes (ingrediente+)>
    <!ELEMENT ingrediente (nombre,cantidad?)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ATTLIST cantidad unidad (gramos|mililitros|cucharada|chorro|pizca) #IMPLIED>
    <!ELEMENT instrucciones (paso+)>
    <!ELEMENT paso (#PCDATA)>
]>        
<receta plato="primero" xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='11.xsd'>
    <nombre>Risotto milanesa</nombre>
    <descripcion>Risotto milanesa : Plato tipico de Italia</descripcion>
    <tiempo preparacion="50" coccion="20"/>
    <ingredientes>
        <ingrediente>
            <nombre>Arroz</nombre>
            <cantidad unidad="gramos">500</cantidad>
        </ingrediente>
         <ingrediente>
            <nombre>Cebolla mediana</nombre>
            <cantidad>1</cantidad>
        </ingrediente>
         <ingrediente>
            <nombre>Azafran</nombre>
            <cantidad unidad="pizca">1</cantidad>
        </ingrediente>
         <ingrediente>
            <nombre>Queso parmesano</nombre>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
         <ingrediente>
            <nombre>Mantequilla</nombre>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
         <ingrediente>
            <nombre>Sal</nombre>
        </ingrediente>
         <ingrediente>
            <nombre>Pimienta</nombre>
        </ingrediente>
         <ingrediente>
            <nombre>Caldo</nombre>
            <cantidad unidad="mililitros">1000</cantidad>
        </ingrediente>
         <ingrediente>
            <nombre>Vino blanco</nombre>
            <cantidad unidad="chorro">1</cantidad>
        </ingrediente>
    </ingredientes>
    <instrucciones>
        <paso>
            Picamos la cebolla y la pochamos con la mitad
            de la mantequilla.
        </paso>
        <paso> 
            Cuando esté transparente, echamos el azafrán,
            el vino y dejamos que reduzca.
        </paso>
        <paso>
            A continuación, incorporamos el arroz, lo
            sofreímos un poco.
        </paso>
        <paso>
            Vamos añadiendo el caldo caliente poco a poco
            mientras removemos.
        </paso>
        <paso>
            Salpimentamos.
        </paso>
        <paso>
            Cuando esté casi hecho, agregamos el resto de
            la mantequilla y el queso.
        </paso>
        <paso>
            Servimos enseguida.
        </paso>
    </instrucciones>
</receta>
