=== Manuel0119/2122_LMSGI_ManuelMA/EX02_20220324_ManuelMartinAlonso/tabla.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT tabla_periodica (atomo+)>
<!ATTLIST tabla_periodica 
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED>
<!ELEMENT atomo (nombre,simbolo,num_atomico,valencias?,peso_atomico,punto_ebu?,punto_fus?,densidad?)>
<!ATTLIST atomo periodo CDATA #REQUIRED
                grupo CDATA #REQUIRED
                bloque (s|p|d|f) #REQUIRED> 
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT simbolo (#PCDATA)>
<!ELEMENT num_atomico (#PCDATA)>
<!ELEMENT valencias (valencia*)>
<!ELEMENT valencia (#PCDATA)>
<!ELEMENT peso_atomico (#PCDATA)>
<!ELEMENT punto_ebu (#PCDATA)>
<!ATTLIST punto_ebu unidades CDATA #REQUIRED>
<!ELEMENT punto_fus (#PCDATA)>
<!ATTLIST punto_fus unidades CDATA #REQUIRED>
<!ELEMENT densidad EMPTY>
<!ATTLIST densidad valor CDATA #REQUIRED>

=== Manuel0119/2122_LMSGI_ManuelMA/EX02_20220324_ManuelMartinAlonso/tabla.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE tabla_periodica SYSTEM "tabla.dtd">
<tabla_periodica xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='tabla.xsd'>
    <atomo periodo="1" grupo="1" bloque="s">
        <nombre>Hidr√≥geno</nombre>
        <simbolo>H</simbolo>
        <num_atomico>1</num_atomico>
        <valencias>
            <valencia>1</valencia>
        </valencias>
        <peso_atomico>1.00797</peso_atomico>
        <punto_ebu unidades="K">20.268</punto_ebu>
        <punto_fus unidades="K">14.025</punto_fus>
        <densidad valor="0,071"/>
    </atomo>
    <atomo periodo="5" grupo="8" bloque="d">
        <nombre>Rutenio</nombre>
        <simbolo>Ru</simbolo>
        <num_atomico>44</num_atomico>
        <valencias>
            <valencia>2</valencia>
            <valencia>3</valencia>
            <valencia>4</valencia>
            <valencia>6</valencia>
            <valencia>8</valencia>
        </valencias>
        <peso_atomico>101.07</peso_atomico>
        <punto_ebu unidades="C">4900</punto_ebu>
        <punto_fus unidades="C">2500</punto_fus>
        <densidad valor="12,2"></densidad>
    </atomo>
    <atomo periodo="6" grupo="17" bloque="p">
        <nombre>Astato</nombre>
        <simbolo>At</simbolo>
        <num_atomico>85</num_atomico>
        <peso_atomico>85</peso_atomico>
        <punto_fus unidades="C">302</punto_fus>
    </atomo>
</tabla_periodica>
